---
driver:
  name: vagrant

  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
#    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      customize:
        memory: 1024

#  - name: ubuntu-14.04
#  - name: centos-7.1
#  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[awesome_app::default]
    attributes:
