---
driver:
  name: vagrant
  name: digitalocean
  # name: docker
  # require_chef_omnibus: true

  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]
#    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
# Docker platform specifics
  # - name: ubuntu-12.04
  #   driver_config:
  #     image: ubuntu:12.04
  #     socket: tcp://192.168.99.100:2376
  #     use_cache: true
  #   driver:
  #     use_sudo: false
  #     # share your workstation's cookbooks with the Docker container
  #     volume: ~/play_chef/chef-repo/cookbooks:/mnt/host-cookbooks
  #     forward:
  #       - 80:80

# Virtualbox specifics
  # - name: ubuntu-12.04
  #   driver_config:
  #     customize:
  #       memory: 1024

# Digital Ocean specifics
  - name: ubuntu-12.04
    driver_config:
      size: 1gb
      region: sfo1

#  - name: ubuntu-14.04
#  - name: centos-7.1
#  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[awesome_app::default]
    attributes:
